### ISSUE TITLE
File transfer issue.

### ISSUE THREAD

**Issue by ghost** [summerwind/node-stun#6]
Hello, did you try to transfer file via node-stun ?
When I send ordinary packeges all is OK, but when I try to send huge file by chunks I receive **response** event but not **message** event.

Here the example what I'm doing:

outputFile.bytesSent = 0;

```
        do {
            var buf = new Buffer(chunkSize);
            var readed = fs.readSync(outputFile.fd, buf, 0, chunkSize, outputFile.bytesSent);
            if(readed < chunkSize) {
                buf = buf.slice(0, readed);
            }

            outputFile.bytesSent += readed;

            stunClient.send(buf, 0, buf.length, clientStunAddress.port, clientStunAddress.address);

            console.log(outputFile.bytesSent, outputFile.size);
        } while(outputFile.bytesSent < outputFile.size);
```

And here the dump of packages (response event, console.log(packet)) what I'm receiving on another side:

{ class: 1,
  method: 256,
  attrs: { '12852': < Buffer 38 31 39 38 36 32 37 32 0a 31 39 39 30 38 36 31 39 35 38 0a 37 30 39 34 37 39 36 33 0a 31 38 39 32 32 31 37 36 36 35 0a 31 32 34 36 38 30 34 34 33 35 ... > },
  tid: 808857905 }
{ class: 1,
  method: 16,
  attrs: { '13874': < Buffer 33 32 34 0a 31 39 31 39 35 30 31 31 0a 34 32 36 34 37 33 38 38 37 0a 37 37 36 36 35 35 36 34 36 0a 31 32 34 31 35 38 30 35 37 33 0a 35 32 32 38 36 32 ... > },
  tid: 170998073 }
{ class: 1,
  method: 16,
  attrs: { '14640': < Buffer 32 0a 31 31 35 31 32 32 33 37 38 30 0a 38 32 39 39 36 33 36 36 39 0a 36 31 31 33 35 33 33 31 31 0a 32 30 32 39 32 31 31 38 30 34 0a 31 39 35 33 35 30 ... > },
  tid: 171521586 }

**Comment by summerwind** [comment]
This is a bug of `client.send()`.
Please use native `send()` of native **dgram** module.
